name: Deploy releases.rpchat.devcraft.ovh

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
  repository_dispatch:
    types: [remote-trigger]

jobs:
  download:
    name: Create artifact from Cloud Storage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.127.0"
          extended: true

      - name: Install npm Packages
        run: npm ci

      - name: Build Hugo
        run: hugo --minify

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          # location of the coverage artifacts
          path: "./public"

  deploy-webapp:
    name: Deploy webapp to GHPages
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: download

    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
